### ISSUE TITLE
Amount Spent by Month

### ISSUE THREAD

**Issue by igorescobar** [jonluca/RideShare-Trip-Stats#3]
Hey @jonluca thanks so much for this! Really helpful!

This is not an issue but more like a feature request?

I installed the google extension basically to get this answer:
How much do I spent with uber on a monthly basis.

I couldn't get this answer. I could only see the number of rides per month.

Thanks! :)

**Comment by jonluca** [comment]
Sure, I can probably add that. I'll add it in the next couple of days.

**Comment by igorescobar** [comment]
Any instructions to run it locally? I would love to contribute as well :)

**Comment by jonluca** [comment]
It's just a chrome extension so no special instructions! It's just loading the unpacked instructions, you can follow the 3 steps outline [here](https://developer.chrome.com/extensions/getstarted) in the section titled "Create your manifest". Don't actually create the manifest, just select the directory that contains the manifest in this repo.

**Comment by jonluca** [comment]
OK, should be done. Added it in version 1.6, should be live in an hour or so.

**Comment by igorescobar** [comment]
Thanks!
