### ISSUE TITLE
Issue with updating currency.json

### ISSUE THREAD

**Issue by hamza1886** [jonluca/RideShare-Trip-Stats#4]
Updating currency rates in currency.json file makes chrome extension corrupt. I guess this may be 
dues to mismatched hash values after I update currency rate. Please see attached screenshot. 

On clicking "Repair", the extension reverts currency.json to original currency rates. How to update currency rate? Thanks.
![Untitled](https://user-images.githubusercontent.com/11709655/64063084-f42e7200-cc08-11e9-8ab3-784330f10f8a.png)

**Comment by jonluca** [comment]
You can't edit the code from an extension installed via the Chrome Web Store.

You'd have to clone this extension locally, then turn on developer mode and select "Load Unpacked Extension". From there you can make any changes and they'll be fine.
