### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by MFranca** [jonluca/RideShare-Trip-Stats#8]
I've installed on Chrome (Version 83.0.4103.61 64 bits), Windows 10, but it freezes on "Processing API 200 of 315"... No additional warnings are provided. Can you check?
Edit: Actually tested on two different notebooks, the same behavior.

**Comment by jonluca** [comment]
Interesting, I wonder if its something about your account? 

If you open up chrome devtools and look at the network requests, do the last few API requests fail or return a not 2xx HTTP code?

**Comment by MFranca** [comment]
Thanks for the quick reply.
This is the **last request: https://riders.uber.com/api/getTripsForClient**
**All requests are status 200** (I know, odd...)

I've spotted an error on Console, though:
```
RideShareStats.js:95 Uncaught TypeError: Cannot read property 'map' of null
    at Object.success (RideShareStats.js:95)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at A (jquery.js:4)
    at XMLHttpRequest.<anonymous> (jquery.js:4)
```

**Comment by jonluca** [comment]
Cool! this should be pretty easy to fix. I'll give it a shot this weekend

**Comment by jonluca** [comment]
I've submitted an update. If you pull master and install the extension locally it should work now. Otherwise, it'll take a few days for Google to approve the extension and push an update to all users.

**Comment by MFranca** [comment]
It's working. Thank you!
